<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="Alexs-MacBook-Pro.local" name="pytest" skipped="0" tests="1" time="10.708" timestamp="2020-08-25T12:29:26.364564"><testcase classname="" file="pd_parser/tests/test_parse_pd.py" name="pd_parser.tests.test_parse_pd" time="0.000"><error message="collection failure">pd_parser/tests/test_parse_pd.py:32: in &lt;module&gt;
    events = _read_tsv(op.join(basepath, &apos;pd_events.tsv&apos;))
../../software/anaconda3/envs/test/lib/python3.8/site-packages/pd_parser/parse_pd.py:24: in _read_tsv
    if op.getsize(fname) == 0:
../../software/anaconda3/envs/test/lib/python3.8/genericpath.py:50: in getsize
    return os.stat(filename).st_size
E   FileNotFoundError: [Errno 2] No such file or directory: &apos;/Users/alexrockhill/software/anaconda3/envs/test/lib/python3.8/site-packages/pd_parser/tests/data/pd_events.tsv&apos;</error></testcase></testsuite></testsuites>